services:
  - type: web
    name: ai-mitr
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn ai_mitr:app
